### ISSUE TITLE
Tagging Cloudwatch

### ISSUE THREAD

**Issue by martham93** [developmentseed/chip-n-scale-queue-arranger#24]
CloudWatch logs created automatically for chip-n-scale aws resources like the `downloadandpredict` lambda, but these aren't tagged. We should add tagging to these cloudwatch resources so it's easier to monitor costs. 
cc @drewbo

**Comment by drewbo** [comment]
Attempted to add this morning but there are a few blockers that make this more of a challenge:
- Cloudwatch logs can't be tagged via Cloudformation (ref: https://lumigo.io/blog/sar-app-to-propagate-cloudformation-tags-to-unsupported-resources/)
- Testing shows that the log group for the download and predict lambda isn't created at deploy time but will be automatically creation after one function invocation 

Steps to implement:
- Add cloudwatch logs for each lambda function to the cloudformation template
- Tag in a script
